Gallery/Gallery/Models/Image.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Gallery.Models
{
    public class Image
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        [DataType(DataType.Date)]
        public DateTime DateTime { get; set; }
        public byte[] bytePhoto { get; set; }
        public int AlbumId { get; set; }

    }
}

Gallery/Gallery/Controllers/ImagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Gallery.Models;
using Gallery.ViewModels;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace Gallery.Controllers
{
    public class ImagesController : Controller
    {
        private readonly GalleryContext _context;

        public ImagesController(GalleryContext context)
        {
            _context = context;
        }

        // GET: Images
        /*public async Task<IActionResult> Index()
        {
            return View(await _context.Image.ToListAsync());
        }*/

        public async Task<IActionResult> Index(int? id, string NameSearch = null, string LocationSearch = null, string DaySearch = null,
        string MonthSearch = null, string YearSearch = null)
        {
            //var img = from i in _context.Image join a in _context.Album on i.AlbumName equals a.Name where a.Id == id select i; 
            var img = _context.Image.Where(x => x.AlbumId == id);

            if (!String.IsNullOrEmpty(NameSearch))
            {
                img = img.Where(s => s.Name.Contains(NameSearch));
            }
            else if (!String.IsNullOrEmpty(LocationSearch))
            {
                img = img.Where(s => s.Location.Contains(LocationSearch));
            }
            else if (!String.IsNullOrEmpty(DaySearch))
            {
                img = img.Where(s => s.DateTime.Day.ToString().Equals(DaySearch));
            }
            else if (!String.IsNullOrEmpty(MonthSearch))
            {
                img = img.Where(s => s.DateTime.Month.ToString().Equals(MonthSearch));
            }
            else if (!String.IsNullOrEmpty(YearSearch))
            {
                img = img.Where(s => s.DateTime.Year.ToString().Equals(YearSearch));
            }

            return View(await img.ToListAsync());
        }

        // GET: Images/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var image = await _context.Image
                .FirstOrDefaultAsync(m => m.Id == id);
            if (image == null)
            {
                return NotFound();
            }

            return View(image);
        }

        // GET: Images/Create
        public IActionResult Create()
        {
            ViewBag.ListOfAlbums = _context.Album.Select(x => x.Name);
            return View();
        }

        // POST: Images/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ImageCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var albumId = _context.Album.Where(s => s.Name == model.AlbumName).Select(x => x.Id).First();
                var image = new Image
                {
                    Name = model.Name,
                    Location = model.Location,
                    DateTime = model.DateTime,
                    AlbumId = albumId
                };
                using (var memoryStream = new MemoryStream())
                {
                    await model.Photo.CopyToAsync(memoryStream);
                    image.bytePhoto = memoryStream.ToArray();
                }
                _context.Add(image);
                await _context.SaveChangesAsync();
                return RedirectToAction("details", new { id = image.Id }); //"details", new { id = newEmployee.Id }
            }
            return View();
        }

        // GET: Images/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ViewData["Albums"] = from x in _context.Album select x;
            var image = await _context.Image.FindAsync(id);
            if (image == null)
            {
                return NotFound();
            }
            return View(image);
        }

        // POST: Images/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Image image)
        {
            if (id != image.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(image);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ImageExists(image.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("details", new { id = image.Id });
            }
            return View(image);
        }

        // GET: Images/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var image = await _context.Image
                .FirstOrDefaultAsync(m => m.Id == id);
            if (image == null)
            {
                return NotFound();
            }

            return View(image);
        }

        // POST: Images/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var image = await _context.Image.FindAsync(id);
            _context.Image.Remove(image);
            await _context.SaveChangesAsync();
            return RedirectToAction("index", new { id = image.AlbumId });
        }

        private bool ImageExists(int id)
        {
            return _context.Image.Any(e => e.Id == id);
        }
    }
}

Gallery/Gallery/Views/Images/Create.cshtml
@model ImageCreateViewModel

@{
    ViewData["Title"] = "Add new photo";
}

<h1>Add new photo</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-controller="Images" asp-action="Create" method="post">
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateTime" class="control-label"></label>
                <input asp-for="DateTime" class="form-control" />
                <span asp-validation-for="DateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AlbumName" class="control-label"></label>
                <select asp-for="AlbumName" class="custom-select">
                    @{ foreach(var item in ViewBag.ListofAlbums)
                        {
                            <option value="@item">@item</option>
                        }
                    }
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Photo" class="control-label"></label>
                <div class="custom-file">
                    <input asp-for="Photo" class="form-control custom-file-input">
                    <label class="custom-file-label">Choose File...</label>
                    <span asp-validation-for="Photo" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-primary" />
                <a asp-controller="Albums" asp-action="Index" class="btn btn-primary">Back</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                var fileName = $(this).val().split("\\").pop();
                $(this).next('.custom-file-label').html(fileName);
            });
        });
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Gallery/Gallery/Views/Images/Delete.cshtml
@model Image

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this photo?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            <p>Name</p>
        </dt>
        <dd class = "col-sm-10">
            @Model.Name
        </dd>
        <dt class = "col-sm-2">
            <p>Location</p>
        </dt>
        <dd class = "col-sm-10">
            @Model.Location
        </dd>
        <dt class = "col-sm-2">
            <p>Date Time</p>
        </dt>
        <dd class = "col-sm-10">
            @Model.DateTime.ToShortDateString()
        </dd>
    </dl>
    
    <form asp-controller="Images" asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-controller="Images" asp-action="Index" asp-route-id="@Model.AlbumId" class="btn btn-primary">Back</a>
    </form>
</div>

Gallery/Gallery/Views/Images/Details.cshtml
@model Image

@{
    ViewData["Title"] = "Details";
}
<div>
    <h1 class="text-center font-weight-bold" style="font-style:oblique;">@Model.Name</h1>
</div>
<div class="row d-flex justify-content-center">
    <h5 class="font-italic mr-2">Location:</h5>
    <h5 class="mr-4">@Model.Location</h5>
    <h5 class="font-italic mr-2">Date:</h5>
    <h5>@Model.DateTime.ToShortDateString()</h5>
</div>

@if (Model != null)
{
    string imageSource = $"data:image;base64,{Convert.ToBase64String(Model.bytePhoto)}";

    <div class="d-flex justify-content-center"><img class="img-fluid" src="@imageSource" asp-append-version="true" /></div>
}
<div class="row d-flex justify-content-center mt-4 mr-2">
    <a asp-controller="Images" asp-action="Index" asp-route-id="@Model.AlbumId" class="btn btn-primary">Back</a>
    <a asp-controller="Images" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
    <a asp-controller="Images" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger">Delete</a>
</div>

Gallery/Gallery/Views/Images/Edit.cshtml
@model Image

@{
    ViewData["Title"] = "Edit";
    var albums = ViewData["Albums"] as IEnumerable<Album>;
}

<h1>Edit Photo</h1>
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-controller="Images" asp-action="Edit">
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateTime" class="control-label">Date Time</label>
                <input asp-for="DateTime" class="form-control" />
                <span asp-validation-for="DateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AlbumId" class="control-label">Album</label>
                <select asp-for="AlbumId" class="custom-select">
                    @{ foreach (var item in albums)
                        {
                            <option value="@item.Id">@item.Name</option>
                        }
                    }
                </select>
            </div>
            <input type="hidden" asp-for="bytePhoto" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-controller="Images" asp-action="Index" asp-route-id="@Model.AlbumId" class="btn btn-primary">Back</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Gallery/Gallery/Views/Images/Index.cshtml
@model IEnumerable<Image>

@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <div class="d-flex justify-content-between">
            <a class="btn btn-lg btn-primary" asp-controller="Images" asp-action="Create">Upload</a>
            <form class="dropdown show" asp-controller="Images" asp-action="Index" method="get">
                <button class="btn btn-lg btn-secondary dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Search
                </button>
                <div class="dropdown-menu">
                    <input class="dropdown-item" type="text" name="NameSearch" placeholder="Name search..." />
                    <input class="dropdown-item" type="text" name="LocationSearch" placeholder="Location search..." />
                    <input class="dropdown-item" type="text" name="DaySearch" placeholder="Day search..." />
                    <input class="dropdown-item" type="text" name="MonthSearch" placeholder="Month search..." />
                    <input class="dropdown-item" type="text" name="YearSearch" placeholder="Year search..." />
                    <div class="dropdown-divider"></div>
                    <input class="dropdown-item text-center" value="Search" type="submit" />
                </div>
            </form>
    </div>
    <div class="card-deck">
            @foreach (var item in Model)
            {
                if (item.bytePhoto != null && item.bytePhoto.Length > 0)
                {
                    string imageSource = $"data:image;base64,{Convert.ToBase64String(item.bytePhoto)}";

                    <div class="card m-3" style="min-width: 18rem; max-width:30.5%;">
                        <div class="thumbnail">
                            <a asp-controller="Images" asp-action="Details" asp-route-id="@item.Id">
                                <img class="rounded img-thumbnail" src="@imageSource"
                                     asp-append-version="true" />
                            </a>
                        </div>
                    </div>
                }
            }
    </div>
    <div>
            <a asp-controller="Albums" asp-action="Index" class="btn btn-primary">Back</a>
    </div>
 </div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}